<?php

namespace App\Filament\Widgets;

use Filament\Widgets\Widget;

class UserManual extends Widget
{
    protected static string $view = 'filament.widgets.user-manual';

    public static function canView(): bool
    {
        $admin = auth()->user()->hasRole('Super Admin');

        return $admin; // TODO: Change the autogenerated stub
    }

}
